#ifndef CLIB_TEMPLATE_DATA_STRUCTURES_NULLPTR
#define CLIB_TEMPLATE_DATA_STRUCTURES_NULLPTR

#ifndef CLIB_NULLPTR
#define CLIB_NULLPTR ((void*) 0x0)
#endif

#endif // end if CLIB_TEMPLATE_DATA_STRUCTURES_NULLPTR
