#ifndef PhiOS_DATA_STRUCTURES_PREPROCESSOR
#define PhiOS_DATA_STRUCTURES_PREPROCESSOR

#define C_TEMPLATE_DATA_STRUCTURES_CONCAT2(x, y) x ## y
#define C_TEMPLATE_DATA_STRUCTURES_CONCAT(x, y) C_TEMPLATE_DATA_STRUCTURES_CONCAT2(x, y)

#endif // end if PhiOS_DATA_STRUCTURES_PREPROCESSOR
